apiVersion: v2
appVersion: v1.7.0
description: Elasticsearch stats exporter for Prometheus
home: https://github.com/prometheus-community/elasticsearch_exporter
keywords:
  - metrics
  - elasticsearch
  - monitoring
kubeVersion: ">=1.10.0-0"
maintainers:
  - email: sven.mueller@commercetools.com
    name: svenmueller
  - email: cedric@desaintmartin.fr
    name: desaintmartin
  - email: rootsandtrees@posteo.de
    name: zeritti
name: prometheus-elasticsearch-exporter
sources:
  - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter
version: 5.8.0-suse-observability.4
dependencies:
  - name: suse-observability-sizing
    repository: file://../suse-observability-sizing
    version: 0.1.2
