{{- $kubeStateOverridden := (include "stackstate-agent.agent.kube-state-metrics.overridden" $) }}
{{- $clusterCheckKSM := and (and .Values.clusterChecks.enabled (or .Values.dependencies.kubeStateMetrics.enabled .Values.clusterChecks.kubeStateMetrics.url)) (not $kubeStateOverridden) }}
{{- if or .Values.agent.config.override $clusterCheckKSM }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-node-agent
  labels:
{{ include "stackstate-agent.labels" . | indent 4 }}
    app.kubernetes.io/component: node-agent
data:
{{-  if $clusterCheckKSM }}
  _etc_stackstate-agent_conf.d_kubernetes_state.d_auto_conf.yaml: |
{{- end }}
{{- range .Values.agent.config.override }}
  {{ .path | replace "/" "_"}}_{{ .name }}: |
{{ .data | indent 4 -}}
{{- end -}}
{{- end -}}
